### ISSUE TITLE
Update the airports database

### ISSUE THREAD

**Issue by simno** [mivek/MetarParser#145]
**Is your feature request related to a problem? Please describe.**
The current `airports.dat` file does not contain some airport codes such as GQNO. This causes the parser to fail when processing any events from this airport.

**Describe the solution you'd like**
Update the `airports.dat` file with the latest [openflights](https://openflights.org/data.html) data

**Comment by mivek** [comment]
Hello @simno 
The list of airports has been updated. 
The fix has been merged on the 1.6-SNAPSHOT version
