### ISSUE TITLE
End indicator (=) leads to wrong parse results

### ISSUE THREAD

**Issue by f-loris** [mivek/MetarParser#168]
**Describe the bug**
METAR or TAF reports usually end with a `=`. Currently this is not considered/handled while parsing. E.g. can be found here: https://en.wikipedia.org/wiki/METAR

**To Reproduce**
1. Parse the following METAR: `LOWW 011150Z 27019KT 9999 FEW034 SCT300 13/04 Q1010 NOSIG=`
2. `getNosig()` returns `false` instead of `true`

**Expected behavior**
The parser should safely omit the end indicator while parsing.

**Comment by f-loris** [comment]
I can file a PR for this after https://github.com/mivek/MetarParser/pull/165 is done.

**Comment by mivek** [comment]
Indeed, I reproduced the bug. I think updating the method `AbstractParser#tokenize` or the regex `AbstractParser#TOKENIZE_REGEX` could resolve the problem.
