### ISSUE TITLE
Parsing independent of airport

### ISSUE THREAD

**Issue by f-loris** [mivek/MetarParser#188]
**Is your feature request related to a problem? Please describe.**
Atm, the airport data is incomplete as for example OTHH is missing which makes it impossible to parse messages for it. From my perspective it is painful to keep the airport.dat up to date, especially when the airport related information is not necessary at all.
Can't we make airport related information optional while parsing data?

**Describe the solution you'd like**
Parse METAR or TAF also when no airport exists. Set Airport to null or mark it as `Optional`

https://github.com/mivek/MetarParser/blob/16ef49df170f552e629f33a32f3d60b70d67c62e/src/main/java/io/github/mivek/parser/MetarParser.java#L76

As an alternative we could make it configurable if airport must be set or not.

I'm open to contribute this change!

**Comment by mivek** [comment]
Indeed, the project depends on the airport.dat file, and if the airport is not found the parsing fails. The optimal fix would be to allow the client specify a source for the airports, however it would require a lot of changes in the project.
I think the `Optional` is an acceptable solution for now but a string attribute may be needed in `AbstractWeatherCode` for the icao.
What do you think?

**Comment by f-loris** [comment]
Yes, adding icao definitely makes sense, maybe naming it a bit more generic like `station`?

**Comment by mivek** [comment]
I am ok with `station`

**Comment by mivek** [comment]
Feature available in version `1.10.0` of the project.
