### ISSUE TITLE
Missing wind Unit of measure lead to NPE

### ISSUE THREAD

**Issue by Grogdunn** [mivek/MetarParser#196]
**Describe the bug**
Missing wind Unit of measure lead to NPE

**To Reproduce**
1. Go to 'MetarParserTest'
2. Try to decode "ENLK 081350Z 26026G40 240V300 9999 VCSH FEW025 BKN030 02/M01 Q0996"
3. See error

**Expected behavior**
From NASA documentation (https://www.aviationsystems.arc.nasa.gov/publications/2014/NASA-TM-2014-218385.pdf) if I understand correctly, KT is the "fallback" unit of misure.

**Additional context**
Live METAR data downloaded from https://tgftp.nws.noaa.gov/data/observations/metar/cycles/

**Comment by mivek** [comment]
Solved in #197
