### ISSUE TITLE
Parsing Wind Direction

### ISSUE THREAD

**Issue by PaulWalkerUK** [mivek/MetarParser#2]
When parsing a METAR where the wind is `30005`, the only thing I get back in the Metar object about the direction is "North West". I'd like to be able to get back `300`. 

What do you think about adding this? I don't mind having a go at it if you're in agreement

**Comment by mivek** [comment]
Yes I think it is a good idea. In another version of the project. I added the attribute in the Wind object.

Here is the pull-request https://github.com/mivek/MetarParser/pull/4.
Tell me if it is ok for you

**Comment by mivek** [comment]
I merged the PR.

**Comment by PaulWalkerUK** [comment]
Yep, that did the job, thanks 👍
