### ISSUE TITLE
Do not discard Descriptive Weathercondition field if no weather condition is provided

### ISSUE THREAD

**Issue by Grogdunn** [mivek/MetarParser#200]
**Describe the bug**
Sometimes metar data has not the "Weathercondition" field, but has some descriptive (like thunderstorm) `AGGH 140340Z 05010KT 9999 TS FEW020 SCT021CB BKN300 32/26 Q1010` for instance

**To Reproduce**
1. Try to parse `AGGH 140340Z 05010KT 9999 TS FEW020 SCT021CB BKN300 32/26 Q1010`
1. check "WeatherConditions" field
1. but is null. The TS (ThunderStorms) information is lost.

**Expected behavior**
Preserve the Descriptive information.

**Additional context**
A lot of test form real data

**Comment by mivek** [comment]
Fixed in 1.10.5
