### ISSUE TITLE
Support for Multiple Descriptive

### ISSUE THREAD

**Issue by Grogdunn** [mivek/MetarParser#202]
**Describe the bug**
Metar string like `AGGH 150350Z 800M TSSH SCT018 FEW018CB BKN100 30/26 Q1009` has 2 description, 'ThunderStorms' and 'Shower of'. Keep both.

**To Reproduce**
1. try to parse `AGGH 150350Z 800M TSSH SCT018 FEW018CB BKN100 30/26 Q1009`
1. see only "shower of" as description
1. missing Thunderstorms

**Expected behavior**
See Thunderstorms also in description field

**Additional context**
A lot of field test

**Comment by mivek** [comment]
I would consider this a feature  and do the changes in another branch.
Are you sure this is a valid code, in the specifications that I have read https://www.ofcm.gov/publications/fmh/FMH1/FMH1.pdf, only one descriptor is allowed per weather phenomena

**Comment by Grogdunn** [comment]
Ok for switching branch for the new feature.
I'll do soon as possible.

Yes, I use the https://www.ofcm.gov/publications/fmh/FMH1/fmh1_2019.pdf for reference (2019 review) but in this case is not important.
With your spec in hand, at page "12-5" and "12-6" there are the `Descriptor Qualifier` paragraph. Reading that, I think you can specify multiple "descriptive" fields because (copy paste):
>  Only one descriptor **shall** be coded for each weather phenomena group 

At the point 4 of "descriptive" paragraph there are more information of Thunderstorms symbol, and at the end they say:
> TS shall not be coded with SH

Well, but both are Descriptive token, and yes they can live together but is not recommended.

**Comment by mivek** [comment]
Thank you for the link of the `Federal Meteorological Handbook`, however as you quoted 
> Only one descriptor shall be coded for each weather phenomena group

So having multiple descriptors in a weather condition group is not valid. 
Adding the multi descriptor feature would allow the parsing of invalid metar messages. I prefer to comply to the Handbook's specifications.

**Comment by Grogdunn** [comment]
Ok, but what about the "clue" that the descriptor "SH" can be coded with "TS" (another descriptor)?

Maybe the actual implementation of multiple descriptors can be too permissive, but some descriptors can be coded together.
What do you think?

And yes they say "Only one descriptor **shall** be coded" not "Only one descriptor **must** be coded", with this I think some descriptor can be coded together but I don't find a list of valid "multiple" desciptors.

Without a sort of support a lot of metar strings present in https://tgftp.nws.noaa.gov/data/observations/metar/cycles/ is "not valid" or has a "lack" of information.
