### ISSUE TITLE
VCSH ignored

### ISSUE THREAD

**Issue by lrh15** [mivek/MetarParser#238]
**Describe the bug**
When parsing a METAR string, the VCSH weather condition is ignored. VCFG and VCTS work fine.

**To Reproduce**
1 - Decode any METAR string with a VCSH weather condition.
```Java
MetarService metarService = MetarService.getInstance();
Metar metar = metarService.decode("ENLK 081350Z 26026G40 240V300 9999 VCSH FEW025 BKN030 02/M01 Q0996");
System.out.println("wc:" +metar.getWeatherConditions());
```
`wc:[]`

**Expected behavior**
Get the list of weather conditions containing the shower in vicinity of the aerodrome.

**Comment by mivek** [comment]
Hello @lrh15 

`VCSH` is now a valid WeatherCondition.
You can update to version `2.2.1` of the project.
