### ISSUE TITLE
Option to disable Information Messages

### ISSUE THREAD

**Issue by Developer66** [mivek/MetarParser#240]
It would be nice to dis/enable such messages in Command line:

Apr 23, 2021 11:21:51 PM io.github.mivek.command.remark.DefaultCommand execute
INFORMATION: Remark token "$" is unknown.

Apr 23, 2021 11:21:51 PM io.github.mivek.command.remark.DefaultCommand execute
INFORMATION: Remark token "T00101009" is unknown.

Apr 23, 2021 11:21:51 PM io.github.mivek.command.remark.DefaultCommand execute
INFORMATION: Remark token "51008" is unknown.

**Comment by mivek** [comment]
Hello @Developer66 

I added these logs in case the remarkparser was not able to parse a remark but they are not as useful as expected.
I will just remove them

**Comment by Developer66** [comment]
Thank you very much.

**Comment by mivek** [comment]
@Developer66 

Logs are removed in version 2.2.3
