### ISSUE TITLE
remarks processing is missing some descriptions..

### ISSUE THREAD

**Issue by BradWalker** [mivek/MetarParser#277]
It would be great if MetarParser supported the following remark:

KCOT 292020Z AUTO 13009KT 3SM TSRA BR SCT011 BKN028 OVC043 23/21 
A2991 RMK AO2 PK WND 13029/2000 **LTG DSNT ALQDS** P0020 

The LTG DSNT ALQDS is translated as: _Lightning distant all quadrants_

Keep up the great work!

**Comment by mivek** [comment]
Hello @BradWalker 

This is fixed in version 2.5.0 of the project.

**Comment by BradWalker** [comment]
> This is fixed in version 2.5.0 of the project.

Hey @mivek , as usual. Thanks for all your efforts!!
