### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by Vacxe** [mivek/MetarParser#291]
```
TAF TAF 
AMD YWLM 270723Z 2707/2806 19020G30KT 9999 -SHRA SCT015 BKN020 
BECMG 2708/2710 19014KT 9999 -SHRA SCT010 BKN015 
BECMG 2800/2802 18015G25KT 9999 -SHRA SCT015 BKN020 
TEMPO 2707/2712 3000 SHRA SCT005 BKN010 INTER 2712/2802 4000 SHRA SCT005 BKN010
```

Last tempos after parsing contains from TEMPO `SHRA SCT005 BKN010` +  from INTER `SHRA SCT005 BKN010`

**Comment by mivek** [comment]
Hello @Vacxe 

INTER is not currently parsed. I'll add it in the next release.

**Comment by mivek** [comment]
Hello @Vacxe 

`INTER` are now parsed. You can update to version 2.6.0.
