### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by PaulWalkerUK** [mivek/MetarParser#3]
I'm interested in using this library as part of a piece of software I'm writing. I haven't decided yet whether I'll keep it private for personal use or make it public via GitHub. However, I'm conscious that there isn't a license included with your library. 

My understanding is that without a license granting permission, I can't technically use it (see for example https://choosealicense.com/no-permission/). Please could you consider adding a license to the project (https://choosealicense.com/ is pretty good at summarising the options)?

**Comment by mivek** [comment]
I just added a LICENSE.md file.
