### ISSUE TITLE
NPE when getting Vertical Visibility

### ISSUE THREAD

**Issue by simno** [mivek/MetarParser#37]
The value for fVerticalVisibility in the AbstractWeatherContainer is stored as an Integer, but the return type of the getVerticalVisibility is an int.

This causes a NullPointerException if we call the getVerticalVisibility function when the fVerticalVisibility has never been set.

```
Exception in thread "main" java.lang.NullPointerException
	at com.mivek.model.AbstractWeatherContainer.getVerticalVisibility(AbstractWeatherContainer.java:107)
        ...
```

I think the return type of the getVerticalVisibility should be changed to Integer, to allow the user to handle null values for the fVerticalVisibility.

**Comment by mivek** [comment]
Yes indeed, you are right. I'll correct this.
