### ISSUE TITLE
Remarks section is missing some translations

### ISSUE THREAD

**Issue by BradWalker** [mivek/MetarParser#394]
**Describe the bug**
Given the following METAR:

"KCOT 292020Z AUTO 13009KT 3SM TSRA BR SCT011 BKN028 OVC043 23/21 A2991 RMK AO2 PK WND 13029/2000 LTG DSNT ALQDS P0020";

MetarParser doesn't fully parse the remark section.

Here is what I see:

io.github.mivek.model.Metar@61baa894[day of the month=29,time of report=20:20,airport=Cotulla-La Salle County Airport (KCOT),speed=9,unit=KT,direction=South East,direction (degrees)=130,gusts=0,minimal wind variation=0,maximal wind variation=0,main visibility=3SM,minimum visibility=0,minimum visibility direction=<null>,vertical visibility (ft)=<null>,clouds=[io.github.mivek.model.Cloud@5b1d2887[quantity=scattered,type=<null>,height (ft)=1100], io.github.mivek.model.Cloud@1c2c22f3[quantity=broken,type=<null>,height (ft)=2800], io.github.mivek.model.Cloud@33e5ccce[quantity=overcast,type=<null>,height (ft)=4300]],weather conditions=[io.github.mivek.model.WeatherCondition@270421f5[intensity=<null>,descriptive=thunderstorm,phenomenons=[rain]], io.github.mivek.model.WeatherCondition@4f4a7090[intensity=<null>,descriptive=<null>,phenomenons=[mist]]],cavok=false,remarks=automated station with a precipitation discriminator peak wind of 29 knots from 130 degrees at 20:00 **LTG DSNT ALQDS P0020** ,original message=KCOT 292020Z AUTO 13009KT 3SM TSRA BR SCT011 BKN028 OVC043 23/21 A2991 RMK AO2 PK WND 13029/2000 LTG DSNT ALQDS P0020,temperature (°C)=23,dew point=21,altimeter (hPa)=1012,nosig=false,auto=true,runways information=[],trends=[]]

According to FEDERAL METEOROLOGICAL HANDBOOK No. 1, Surface Weather Observations and Reports, page 12-9

**Expected behavior**

I would have expected the following output

LTG - lighting
DSNT - Distant
ALQDS - All Quadrants (* U.S. National Weather Service approved abbrivation *)..

**Additional context**

**Comment by mivek** [comment]
Hello @BradWalker 

I do not reproduce the bug. When I parse the METAR code on [https://www.metar-taf-decoder.com/](https://www.metar-taf-decoder.com) I get the following for the remark.

`Remark: automated station with a precipitation discriminator peak wind of 29 knots from 130 degrees at 20:00 lightning distant all quadrants 20/100 of an inch of precipitation fell in the last hour `

Which version of the parser are you using ?

**Comment by BradWalker** [comment]
Hey @mivek ,

Thanks for the prompt response! You're right. I was not using the latest version in my pom.xml file..

Thanks again for all your efforts with this software!
