### ISSUE TITLE
problem with class file version

### ISSUE THREAD

**Issue by BradWalker** [mivek/MetarParser#395]
**Describe the bug**
Apparently something in the compile of metarParser-services is giving me isssues.. When I use version 2.6.1 of metarParser-services
in my Android project it works fine. But, when I use 2.7.1 or higher, I get the following error.

/home/bwalker/AndroidStudioProjects/OkHttp/app/src/main/java/com/journaldev/AvareOkHttpTest/MainActivity.java:12: error: cannot access Metar
import io.github.mivek.model.Metar;
                            ^
  bad class file: /home/bwalker/.gradle/caches/transforms-3/00ed7a1ddaa9e24a9790af71ba98ddce/transformed/jetified-metarParser-entities-2.7.1.jar(/io/github/mivek/model/Metar.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

I'm able to use ver. 2.10.1 of metarParser with no problem..

I've also noticed the same thing when using generic Java. The solution there was to just go to using the Java 17 JDK to compile. But, I did see the same error..

Wanted to let you know.

**Comment by mivek** [comment]
Hello BradWalker

This is not a bug.
Versions <= 1.6.0 used java 1.8 for compilation see the [pom of version 1.6.0](https://github.com/mivek/MetarParser/blob/9db7ae328389b4d83bfc1f3565d13d6988ebce10/pom.xml#L47). 
From version 1.7.0, the java version used for compilation is JDK 17 see [the pom](https://github.com/mivek/MetarParser/blob/2.7.0/pom.xml#L47).

This change was mentioned is the [release note ](https://github.com/mivek/MetarParser/releases/tag/2.7.0).
