### ISSUE TITLE
Update URLs for OurAirports data files to point to suggested GitHub paths

### ISSUE THREAD

**Issue by tkelley-eg** [mivek/MetarParser#407]
**Is your feature request related to a problem? Please describe.**
As of November of last year, the ourairports.com site moved their data files to a github repo.  There is a notice posted on this page:

https://ourairports.com/data/

They currently have a redirect in place, but at some point they could turn that off and the provider would break.

**Describe the solution you'd like**
Update the URLs to the GitHub URLs

**Describe alternatives you've considered**
There are really not alternative solutions since there is a single source for the provider data.

**Additional context**
N/A

Side note : I'm participating in `Hacktoberfest` and would be interested in submitting a PR for this and getting credit if the maintainers are ok with that.

https://hacktoberfest.com/participation/

**Comment by mivek** [comment]
Hello @tkelley-eg 

Thank you for the issue. indeed, the url change will eventually break the project.
You can create a PR to change the URL [here](https://github.com/mivek/MetarParser/blob/master/metarParser-spi/src/main/java/io/github/mivek/provider/airport/impl/OurAirportsAirportProvider.java#L34-L36)
👍
