### ISSUE TITLE
Visibility is not parsed if its in nautical miles

### ISSUE THREAD

**Issue by simno** [mivek/MetarParser#41]
**Describe the bug**
A visibility in a TAF event is not parsed if it is in nautical miles

**To Reproduce**
Parse the following TAF event:
```
TAF CZBF 300939Z 3010/3022 VRB03KT 6SM -SN OVC015 
TEMPO 3010/3012 11/2SM -SN OVC009 FM301200 10008KT 2SM -SN OVC010 
TEMPO 3012/3022 3/4SM -SN VV007 RMK FCST BASED ON AUTO OBS. NXT FCST BY 301400Z
```
**Expected behavior**
The visibility for the main event should be `6SM`, not null
The visibility for the first TEMPO event should be `11/2SM`, not null
The visibility for the second TEMPO event should be `3/4SM`, not null

**Comment by mivek** [comment]
Indeed visibility is only parsed if it is in meters for the moment.
I tag this issue as an enhancement and will be working on it.

**Comment by mivek** [comment]
Would you prefer to have the visibility in nautical miles or can it be converted into metric systems?

**Comment by mivek** [comment]
I created a PR for this issue. 
I let you comment it.
