### ISSUE TITLE
Clouds with "///" cloud type do not parse

### ISSUE THREAD

**Issue by aeharding** [mivek/MetarParser#417]
**Describe the bug**

Cloud groups with "///" do not parse, for example `SKT010///`

**To Reproduce**

Use `EKVG 291550Z AUTO 13009KT 9999 BKN037/// BKN048/// 07/06 Q1009 RMK FEW011/// FEW035/// WIND SKEID 13020KT`, see no clouds found.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/2166114/198842049-a42fd9ee-5bc4-4176-bdf8-781b5896e1c2.png">

**Expected behavior**

Expect two cloud groups, BKN037 BKN048.

**Screenshots**

Expected behavior from aviationweather.gov:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/2166114/198842093-c610f4f7-92eb-40e5-b1ad-58c7404f2870.png">

**Additional context**

This should be fairly easy to fix with a small regex adjustment - see PR and test on the JS implementation:

https://github.com/aeharding/metar-taf-parser/pull/36/files

If you would like, I can try to make a PR for this project (I'm just not too familiar with Java) :)

**Comment by mivek** [comment]
Hello @aeharding 
This is a know issue with the parser https://github.com/mivek/MetarParser/issues/266.

I chose not to implement it because it would allow empty wind elements in the list of wind.
Also the height being an `int`, it cannot be null and has a default value of 0. It would be a wrong information

**Comment by mivek** [comment]
I checked the code. The `height` field is an Integer and allows null value.
I will work on this once the PR about the Icing and the Turbulence is merged

**Comment by aeharding** [comment]
Hi @mivek, thanks for the response. Not rush at all, and by the way, icing/turbulence is looking good!

**Comment by mivek** [comment]
Hi @aeharding 

I opened a PR to fix this.

I did not updated the regular expression to match an unknown height and an unknown cloud type
