### ISSUE TITLE
Parse RMK in TAF event

### ISSUE THREAD

**Issue by simno** [mivek/MetarParser#42]
**Describe the bug**
The remarks in a TAF event are parsed as weather conditions

**To Reproduce**
Parse the following TAF event:
```
TAF CZBF 300939Z 3010/3022 VRB03KT 6SM -SN OVC015 
TEMPO 3010/3012 11/2SM -SN OVC009 FM301200 10008KT 2SM -SN OVC010 
TEMPO 3012/3022 3/4SM -SN VV007 RMK FCST BASED ON AUTO OBS. NXT FCST BY 301400Z
```
**Expected behavior**
The weather conditions should just include light snow, however the 'FC' is being parsed from the RMK string and being interpreted as a funnel cloud.
```
{
    ...
		"weatherConditions": [{
			"valid": true,
			"intensity": "LIGHT",
			"phenomenons": ["SNOW"]
		}, {
			"valid": true,
			"phenomenons": ["FUNNEL_CLOUD"]
		}, {
			"valid": true,
			"phenomenons": ["FUNNEL_CLOUD"]
		}],
		"verticalVisibility": 700
	}],
    ...
}
```
I'm not sure if TAF events should include RMK sections, so maybe it's an operator error by the creator of the TAF event.

**Comment by mivek** [comment]
I know that METAR events can include remarks, I think TAF events can include remarks too.
For now, remarks are not parsed neither in METAR nor in TAF events.

The remark part not easy to parse, I have not found a way to parse it correctly yet

**Comment by mivek** [comment]
Hello @simno, I am now working on the remarks in metar and taf events.

**Comment by mivek** [comment]
@simno remarks are now parsed in TAF and METAR events.
This feature is in version 1.5 of the project.
