### ISSUE TITLE
Visibility not parsed

### ISSUE THREAD

**Issue by tobi3988** [mivek/MetarParser#44]
**Describe the bug**
I try to parse this Metar String:
```
METAR LSZL 300320Z AUTO 00000KT 9999NDV BKN060 OVC074 00/M04 Q1001
RMK=
```
But the visibility 9999 is not parsed? 

**To Reproduce**
Parse above Metar String

**Expected behavior**
I would think that the the visibilty in the metar object is set to 9999.

**Comment by simno** [comment]
It seems like there is a typo in that message and a space should be inserted after the `9999`, so I don't believe this is a bug with the parser, but an error in the data.

**Comment by tobi3988** [comment]
Thanks for your quick answer. I am pretty new to the Metar and Taf, so I do not exactly know, if there is some standard reference/specification for it?

 I got this string from Meteoswiss and on the internet I found some other examples with 9999NDV. So I do not know, if this is an other version of Metar or some additional specification.

For example I found such strings on the following sites:

- http://www.bom.gov.au/standard/ndvncd.shtml
- https://www.aviationweather.gov/metar/data?ids=BGSF&format=decoded&hours=36&taf=on&layout=on&date=0

**Comment by simno** [comment]
Seems like its an Australian standard but I haven't seen it before, also new to METAR & TAF. Looks like it is a bug then :+1:

**Comment by mivek** [comment]
I didn't know this syntax but it is a bug.
Should the NDV information be stored inside the Visibility object?

**Comment by mivek** [comment]
I merged the PR into the develop branch.
Thank you for your help @tobi3988
