### ISSUE TITLE
Deploy to maven central

### ISSUE THREAD

**Issue by piotrpietrzak** [mivek/MetarParser#47]
I'm always frustrated when I would like to use library and there is no easy way to grab it from maven repository.

I would like to suggest that you can deploy lib to maven central.

Or any other public repository you like.

**Comment by mivek** [comment]
Hello @piotrpietrzak, you can now add the `metarParser` directly in your pom.
https://search.maven.org/artifact/io.github.mivek/metarParser/1.3/jar.
I updated the README

**Comment by mivek** [comment]
Could you please confirm that you can add `metarPaser` as a maven dependency?

**Comment by piotrpietrzak** [comment]
Yes - I can confirm. Now it works - not only binary release but also source code. Good job @mivek !
