### ISSUE TITLE
3 letter gust support

### ISSUE THREAD

**Issue by aeharding** [mivek/MetarParser#513]
**Is your feature request related to a problem? Please describe.**

Some METAR reports describe gusts in 3 digits.

**Describe the solution you'd like**

Support for 3 digit gusts

**Describe alternatives you've considered**

None

**Additional context**

Please see the upstream issue, along with more explanation at metar-taf-parser here: https://github.com/aeharding/metar-taf-parser/pull/77

**Comment by mivek** [comment]
Thank you @aeharding, I'll make a PR to add the feature.
