### ISSUE TITLE
Parsing TEMPO clause in METAR

### ISSUE THREAD

**Issue by PaulWalkerUK** [mivek/MetarParser#6]
In the [example in the ReadMe](https://github.com/mivek/MetarParser/blob/3a860c405cc1c948f03f097773ba222423daffe9/README.md#parse-a-metar), it gives a METAR of:

    LFPG 131830Z 19005KT 170V250 9999 -SHRA FEW040TCU SCT086 16/08 Q1011 TEMPO SCT030TCU

Is the `TEMPO` clause being parsed? I can't see any reference to it in the data I get back.

**Comment by PaulWalkerUK** [comment]
No problem, it's only a "nice to have" for me - certainly not a priority for my use-case

**Comment by mivek** [comment]
I am working on the model for this feature.
