### ISSUE TITLE
Parse CAVOK

### ISSUE THREAD

**Issue by simno** [mivek/MetarParser#63]
**Is your feature request related to a problem? Please describe.**
A taf event can contain a CAVOK (Cloud and visibility are ok) signal, this means that the visibility is greater the 10km and there are no significant clouds.
Currently the parser does not make this information accessible to the user.

**Describe the solution you'd like**
Have a boolean possibly, showing that the event contained a CAVOK signal. 

**Describe alternatives you've considered**
Alternatively it could be fixed so that the visibility is set to `>10km`

**Comment by mivek** [comment]
@simno, the cavok feature has been merged into develop and will be in the next release scheduled next week.

**Comment by mivek** [comment]
Version 1.4
