### ISSUE TITLE
Unit for cloud height

### ISSUE THREAD

**Issue by PaulWalkerUK** [mivek/MetarParser#7]
It looks like the cloud height is being converted approximately into metres (the numbers from the METAR are in hundreds of feet, which the library multiplies by 30, to give an approximation for metres). Since the METAR reports it in feet, I'm wondering if this library should return it in the same unit, and just let the user of the library worry about converting it if they want to?

For example, cloud in the METAR as `BKN003` gets the height returned by this library as `90` whereas I originally expected to get `300`.

I don't mind if you want to leave it as it is - I can just convert it back again myself

**Comment by mivek** [comment]
It was a personal choice to convert cloud height in meters but I can add a property to have it in feet.
